D("flatpak.org", REG_GANDI,
    DnsProvider(DNS_GANDI),
    A("@", "3.208.234.181"),
    A("@", "54.210.188.246"),
    MX("@", 10, "smtp.gnome.org."),
    CNAME("docs", "readthedocs.io."),
    CNAME("www", "ingress.openshift.gnome.org."),
    TXT("@", "libera-iE!2PbqoQsUaDXkRDrbAX2_j"),
    TXT("_github-challenge-flatpak-org", "917f6431b5"),
    END);
