D("gnome.gr", REG_GANDI_GR,
    DnsProvider(DNS_GANDI_GR),
    A("@", "8.43.85.3"),
    A("@", "8.43.85.4"),
    A("@", "8.43.85.5"),
    MX("@", 10, "smtp.gnome.org."),
    MX("lists", 10, "smtp.gnome.org."),
    CNAME("wiki", "router-default.apps.openshift4.gnome.org."),
    CNAME("www", "router-default.apps.openshift4.gnome.org."),
    CNAME("planet", "router-default.apps.openshift4.gnome.org."),
    CNAME("www.planet", "router-default.apps.openshift4.gnome.org."),
    CNAME("memory", "pylyglot.info.tm."),
    A("lists", "8.43.85.3"),
    A("lists", "8.43.85.4"),
    A("lists", "8.43.85.5"),
    END);
