D("gtk.org", REG_MONITOR,
    DnsProvider(DNS_CLOUDNS),
    DefaultTTL('1h'),
    ALIAS("@", "dualstack.n.sni.global.fastly.net."),
    MX("@", 10, "smtp.gnome.org."),
    CNAME("www", "dualstack.n.sni.global.fastly.net."),
    CNAME("ftp", "dualstack.n.sni.global.fastly.net."),
    CNAME("docs", "dualstack.n.sni.global.fastly.net."),
    CNAME("beast", "beast.testbit.eu."),
    CNAME("ftp.beast", "beast.gtk.org."),
    CNAME("www.beast", "beast.gtk.org."),
    CNAME("rapicorn", "rapicorn.testbit.eu."),
    CNAME("ftp.rapicorn", "rapicorn.gtk.org."),
    CNAME("www.rapicorn", "rapicorn.gtk.org."),
    CNAME("blog", "blogs.gnome.org."),
    CNAME("_acme-challenge", "m96ji2hmke0c6k3d5r.fastly-validations.com."),
    CNAME("_acme-challenge.ftp", "uxozldew200uocqpz7.fastly-validations.com."),
    END);
