D("guadec.org", REG_GANDI,
    DnsProvider(DNS_GANDI),
    DefaultTTL('1h'),
    ALIAS("@", "ingress.openshift.gnome.org."),
    MX("@", 10, "smtp.gnome.org."),
    CNAME("www", "ingress.openshift.gnome.org."),
    CNAME("2000", "ingress.openshift.gnome.org."),
    CNAME("2001", "ingress.openshift.gnome.org."),
    CNAME("2002", "ingress.openshift.gnome.org."),
    CNAME("2003", "ocp-ingress.fastly.gnome.org."),
    CNAME("2004", "ocp-ingress.fastly.gnome.org."),
    CNAME("2005", "ocp-ingress.fastly.gnome.org."),
    CNAME("2006", "ingress.openshift.gnome.org."),
    CNAME("2007", "ingress.openshift.gnome.org."),
    CNAME("2008", "ingress.openshift.gnome.org."),
    CNAME("2009", "ingress.openshift.gnome.org."),
    CNAME("2010", "ingress.openshift.gnome.org."),
    CNAME("2011", "ingress.openshift.gnome.org."),
    CNAME("2012", "ingress.openshift.gnome.org."),
    CNAME("2013", "ocp-ingress.fastly.gnome.org."),
    CNAME("2014", "ocp-ingress.fastly.gnome.org."),
    CNAME("2015", "ocp-ingress.fastly.gnome.org."),
    CNAME("2016", "ocp-ingress.fastly.gnome.org."),
    CNAME("2017", "ocp-ingress.fastly.gnome.org."),
    CNAME("2018", "ocp-ingress.fastly.gnome.org."),
    CNAME("2019", "ingress.openshift.gnome.org."),
    CNAME("2020", "ingress.openshift.gnome.org."),
    CNAME("2021", "ingress.openshift.gnome.org."),
    CNAME("videos", "1835215117.rsc.cdn77.org."),
    CNAME("registration", "events.gnome.org."),
    CNAME("_acme-challenge", "qgwrijekjz0vj8vaut.fastly-validations.com."),
    END);
