name: Preview changes

on:
  pull_request:
    branches: main
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

permissions:
  pull-requests: write
  contents: read

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: gnome-infra/dnscontrol
          ref: gandi_v5-auth-changes
          path: dnscontrol

      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: dnscontrol/go.sum

      - name: Build dnscontrol
        run: |
          cd dnscontrol
          go build
          ./dnscontrol version
          sudo install -Dm755 dnscontrol /usr/local/bin/dnscontrol

      - name: Run preview
        run:
          dnscontrol --no-colors preview | tee preview_output.txt
        env:
          GANDI_TOKEN: ${{ secrets.GANDI_TOKEN }}

      - name: Post preview to PR
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('preview_output.txt', 'utf8');
            const body = `DNSControl preview:\n\`\`\`\n${output}\n\`\`\`\n\nFull run: ${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body,
            });
